### ISSUE TITLE
AllStop won't destroy a ship

### ISSUE THREAD

**Issue by wortzmanb** [Mikeware/SpaceBattleArena#90]
AllStopCommand will take a ship's health down to zero, but will not destroy the ship.  Not sure if this is because health is a double behind the scenes and thus is not _actually_ getting to zero.

Also, this might be by design.  The student who discovered this did so by trying to repeatedly all-stop so he could self-destruct and respawn somewhere else.

**Comment by hawkerm** [comment]
Yeah, this was because I was just halving the health and there was no tracking on health.  In 1.1 now there's a refactor which fixes this, so I changed AllStop to use the damage method which can destroy the ship.

That's a lot of commands to destroy your ship, you won't have enough energy to do it that way.
